services:
  radicale:
    image: "11notes/radicale:3.1.9"
    container_name: "radicale"
    environment:
      TZ: Europe/Zurich
    ports:
      - "5232:5232/tcp"
    volumes:
      - "etc:/radicale/etc"
      - "var:/radicale/var"
volumes:
  etc:
  var: